# Generated by Django 5.1.1 on 2024-09-29 12:56

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('center', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='BeneficiaryShipment',
            fields=[
                ('BeneficiaryShipment_id', models.CharField(max_length=5, primary_key=True, serialize=False)),
            ],
        ),
        migrations.CreateModel(
            name='Beneficiary',
            fields=[
                ('Benificiary_id', models.CharField(max_length=5, primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=100)),
                ('address', models.TextField(max_length=200)),
                ('Center_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='center.center')),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='BeneficiaryRequest',
            fields=[
                ('BenRequest_id', models.CharField(max_length=5, primary_key=True, serialize=False)),
                ('items', models.TextField(max_length=200)),
                ('description', models.TextField(max_length=200)),
                ('quantity', models.IntegerField()),
                ('timestamp', models.DateTimeField()),
                ('Benificiary_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='donor.beneficiary')),
                ('BeneficiaryShipment_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='donor.beneficiaryshipment')),
            ],
        ),
        migrations.CreateModel(
            name='Donor',
            fields=[
                ('Donor_id', models.CharField(max_length=5, primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=100)),
                ('email', models.EmailField(max_length=254)),
                ('district', models.CharField(max_length=100)),
                ('city', models.CharField(max_length=100)),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='PhoneBeneficiary',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('phonenumber', models.BigIntegerField()),
                ('Beneficiary_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='donor.beneficiary')),
            ],
        ),
        migrations.CreateModel(
            name='PhoneDonor',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('phonenumber', models.BigIntegerField()),
                ('Donor_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='donor.donor')),
            ],
        ),
    ]
