# Generated by Django 5.1.1 on 2024-10-03 10:09

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('donor', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='donor',
            old_name='Donor_id',
            new_name='d_id',
        ),
        migrations.AddField(
            model_name='donor',
            name='address',
            field=models.TextField(null=True),
        ),
        migrations.AddField(
            model_name='donor',
            name='pincode',
            field=models.CharField(blank=True, max_length=6, null=True),
        ),
        migrations.AlterField(
            model_name='phonedonor',
            name='Donor_id',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='donor.donor'),
        ),
    ]
