# Generated by Django 5.1.1 on 2024-10-03 10:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('donor', '0002_rename_donor_id_donor_d_id_donor_address_and_more'),
    ]

    operations = [
        migrations.RenameField(
            model_name='phonedonor',
            old_name='Donor_id',
            new_name='donor',
        ),
        migrations.RemoveField(
            model_name='phonedonor',
            name='phonenumber',
        ),
        migrations.AddField(
            model_name='phonedonor',
            name='number',
            field=models.CharField(max_length=10, null=True),
        ),
    ]
