# Generated by Django 5.1.1 on 2024-10-13 07:27

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('center', '0003_alter_center_email'),
        ('donor', '0003_rename_donor_id_phonedonor_donor_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='beneficiary',
            name='Center_id',
        ),
        migrations.RemoveField(
            model_name='beneficiary',
            name='user',
        ),
        migrations.RemoveField(
            model_name='beneficiaryrequest',
            name='Benificiary_id',
        ),
        migrations.RemoveField(
            model_name='beneficiaryrequest',
            name='BeneficiaryShipment_id',
        ),
        migrations.AddField(
            model_name='beneficiaryrequest',
            name='Center_id',
            field=models.ForeignKey(default=101, on_delete=django.db.models.deletion.CASCADE, to='center.center'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='beneficiaryrequest',
            name='address',
            field=models.TextField(default='kerala', max_length=200),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='beneficiaryrequest',
            name='name',
            field=models.CharField(default='defaultname', max_length=100),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='beneficiaryrequest',
            name='phonenumber',
            field=models.BigIntegerField(default=1243241),
            preserve_default=False,
        ),
        migrations.DeleteModel(
            name='PhoneBeneficiary',
        ),
        migrations.DeleteModel(
            name='Beneficiary',
        ),
        migrations.DeleteModel(
            name='BeneficiaryShipment',
        ),
    ]
