# Generated by Django 5.1.1 on 2024-10-14 13:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('donor', '0005_beneficiaryrequest_email'),
    ]

    operations = [
        migrations.AddField(
            model_name='beneficiaryrequest',
            name='pincode',
            field=models.CharField(max_length=6, null=True),
        ),
    ]
