# Generated by Django 5.1.1 on 2024-10-28 17:10

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('donor', '0006_beneficiaryrequest_pincode'),
    ]

    operations = [
        migrations.DeleteModel(
            name='BeneficiaryRequest',
        ),
    ]
