# Generated by Django 5.1.1 on 2024-10-30 14:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('donor', '0007_delete_beneficiaryrequest'),
    ]

    operations = [
        migrations.AddField(
            model_name='donor',
            name='latitude',
            field=models.FloatField(null=True),
        ),
        migrations.AddField(
            model_name='donor',
            name='longitude',
            field=models.FloatField(null=True),
        ),
    ]
