# Generated by Django 5.1.1 on 2024-10-31 11:17

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('center', '0011_alter_inventory_inventory_id'),
        ('donor', '0008_donor_latitude_donor_longitude'),
    ]

    operations = [
        migrations.AddField(
            model_name='donor',
            name='center',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.PROTECT, to='center.center'),
        ),
    ]
