# Generated by Django 5.1.1 on 2024-11-01 15:14

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('donor', '0009_donor_center'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='donor',
            name='center',
        ),
    ]
