# Generated by Django 5.1.1 on 2024-09-29 12:56

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('center', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='ItemType',
            fields=[
                ('type_id', models.CharField(max_length=20, primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=100)),
                ('description', models.TextField(default='enter description')),
                ('timestamp', models.DateTimeField()),
            ],
        ),
        migrations.CreateModel(
            name='ItemPickup',
            fields=[
                ('Pickup_id', models.CharField(max_length=5, primary_key=True, serialize=False)),
                ('quantity', models.IntegerField()),
                ('timestamp', models.DateTimeField()),
                ('description', models.TextField()),
                ('Center_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='center.center')),
                ('Volounteer_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='center.volounteer')),
            ],
        ),
        migrations.CreateModel(
            name='ItemReceive',
            fields=[
                ('Itemreceive_id', models.CharField(max_length=5, primary_key=True, serialize=False)),
                ('quantity', models.IntegerField()),
                ('timestamp', models.DateTimeField()),
                ('description', models.TextField()),
                ('Volounteer_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='center.volounteer')),
            ],
        ),
        migrations.CreateModel(
            name='Items',
            fields=[
                ('Item_id', models.CharField(max_length=5, primary_key=True, serialize=False)),
                ('Pickup_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='item.itempickup')),
            ],
        ),
    ]
