# Generated by Django 5.1.1 on 2024-10-07 08:14

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('donor', '0003_rename_donor_id_phonedonor_donor_and_more'),
        ('item', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='itemreceive',
            name='image',
            field=models.ImageField(blank=True, null=True, upload_to=''),
        ),
        migrations.AddField(
            model_name='itemreceive',
            name='isReceived',
            field=models.BooleanField(default=False),
        ),
        migrations.AlterField(
            model_name='itempickup',
            name='timestamp',
            field=models.DateTimeField(auto_now_add=True),
        ),
        migrations.AlterField(
            model_name='itemtype',
            name='description',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='itemtype',
            name='timestamp',
            field=models.DateTimeField(auto_now_add=True),
        ),
        migrations.CreateModel(
            name='DonorRequest',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('quantity', models.IntegerField()),
                ('donor', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='donor.donor')),
                ('item_type', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='item.itemtype')),
            ],
        ),
    ]
