# Generated by Django 5.1.1 on 2024-10-08 08:05

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('item', '0002_itemreceive_image_itemreceive_isreceived_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='donorrequest',
            name='image',
            field=models.ImageField(null=True, upload_to='donation/'),
        ),
        migrations.AddField(
            model_name='itempickup',
            name='donor_request',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, to='item.donorrequest'),
        ),
    ]
