# Generated by Django 5.1.1 on 2024-10-08 08:21

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('item', '0003_donorrequest_image_itempickup_donor_request'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='items',
            name='Pickup_id',
        ),
        migrations.DeleteModel(
            name='ItemPickup',
        ),
        migrations.DeleteModel(
            name='Items',
        ),
    ]
