# Generated by Django 5.1.1 on 2024-10-08 08:24

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('center', '0003_alter_center_email'),
        ('item', '0004_remove_items_pickup_id_delete_itempickup_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='ItemPickup',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('quantity', models.IntegerField()),
                ('timestamp', models.DateTimeField(auto_now_add=True)),
                ('description', models.TextField()),
                ('Center_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='center.center')),
                ('Volounteer_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='center.volounteer')),
                ('donor_request', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, to='item.donorrequest')),
            ],
        ),
    ]
