# Generated by Django 5.1.1 on 2024-10-08 08:32

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('item', '0005_itempickup'),
    ]

    operations = [
        migrations.RenameField(
            model_name='itempickup',
            old_name='Center_id',
            new_name='center',
        ),
        migrations.RenameField(
            model_name='itempickup',
            old_name='Volounteer_id',
            new_name='volunteer',
        ),
        migrations.RemoveField(
            model_name='itempickup',
            name='quantity',
        ),
    ]
