# Generated by Django 5.1.1 on 2024-10-28 17:10

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('donor', '0007_delete_beneficiaryrequest'),
        ('item', '0007_remove_itempickup_description_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='itempickup',
            name='donor_request',
        ),
        migrations.RenameField(
            model_name='itempickup',
            old_name='timestamp',
            new_name='requested_at',
        ),
        migrations.AddField(
            model_name='itempickup',
            name='description',
            field=models.TextField(null=True),
        ),
        migrations.AddField(
            model_name='itempickup',
            name='donor',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='donor.donor'),
        ),
        migrations.AddField(
            model_name='itempickup',
            name='image',
            field=models.ImageField(null=True, upload_to='item_pickup/'),
        ),
        migrations.AddField(
            model_name='itempickup',
            name='isAccepted',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='itempickup',
            name='item_type',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.PROTECT, to='item.itemtype'),
        ),
        migrations.AddField(
            model_name='itempickup',
            name='quantity',
            field=models.IntegerField(null=True),
        ),
        migrations.DeleteModel(
            name='DonorRequest',
        ),
    ]
