# Generated by Django 5.1.1 on 2024-10-29 03:42

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('item', '0008_remove_itempickup_donor_request_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='itempickup',
            name='volunteer',
        ),
    ]
