# Generated by Django 5.1.1 on 2024-10-30 14:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('item', '0009_remove_itempickup_volunteer'),
    ]

    operations = [
        migrations.AlterField(
            model_name='itemreceive',
            name='timestamp',
            field=models.DateTimeField(auto_now_add=True),
        ),
    ]
