# Generated by Django 5.1.1 on 2024-10-31 14:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('item', '0011_remove_itemreceive_itemreceive_id_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='itempickup',
            name='forPickup',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='itempickup',
            name='isPicked',
            field=models.BooleanField(default=False),
        ),
    ]
