# Generated by Django 5.1.1 on 2024-09-29 12:56

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='CenterShipment',
            fields=[
                ('CenterShipment_id', models.CharField(max_length=5, primary_key=True, serialize=False)),
                ('timestamp', models.DateTimeField()),
                ('agent', models.CharField(max_length=50)),
            ],
        ),
        migrations.CreateModel(
            name='Center',
            fields=[
                ('Center_id', models.CharField(max_length=5, primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=200)),
                ('email', models.EmailField(max_length=254)),
                ('isMain', models.BooleanField()),
                ('City', models.CharField(max_length=200)),
                ('State', models.CharField(max_length=200)),
                ('host', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='CenterRequest',
            fields=[
                ('CenterReq_id', models.CharField(max_length=5, primary_key=True, serialize=False)),
                ('description', models.TextField(max_length=200)),
                ('quantity', models.IntegerField()),
                ('Center_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='center.center')),
                ('Shipment_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='center.centershipment')),
            ],
        ),
        migrations.CreateModel(
            name='PhoneCenter',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('phonenumber', models.BigIntegerField()),
                ('Center_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='center.center')),
            ],
        ),
        migrations.CreateModel(
            name='Volounteer',
            fields=[
                ('Volounteer_id', models.CharField(max_length=5, primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=100)),
                ('address', models.CharField(max_length=100)),
                ('email', models.EmailField(max_length=254)),
                ('qualification', models.TextField()),
                ('designation', models.TextField()),
                ('Center_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='center.center')),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='PhoneVolounteer',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('phonenumber', models.BigIntegerField()),
                ('Volounteer_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='center.volounteer')),
            ],
        ),
    ]
