# Generated by Django 5.1.1 on 2024-10-02 16:22

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('center', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='phonecenter',
            name='Center_id',
        ),
        migrations.RenameField(
            model_name='phonevolounteer',
            old_name='Volounteer_id',
            new_name='volunteer',
        ),
        migrations.RenameField(
            model_name='volounteer',
            old_name='Volounteer_id',
            new_name='v_id',
        ),
        migrations.RemoveField(
            model_name='center',
            name='Center_id',
        ),
        migrations.RemoveField(
            model_name='center',
            name='host',
        ),
        migrations.RemoveField(
            model_name='phonevolounteer',
            name='phonenumber',
        ),
        migrations.RemoveField(
            model_name='volounteer',
            name='address',
        ),
        migrations.AddField(
            model_name='center',
            name='CenterID',
            field=models.CharField(default='C00', max_length=4, primary_key=True, serialize=False),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='phonevolounteer',
            name='number',
            field=models.CharField(blank=True, max_length=10, null=True),
        ),
        migrations.AddField(
            model_name='volounteer',
            name='city',
            field=models.CharField(max_length=100, null=True),
        ),
        migrations.AddField(
            model_name='volounteer',
            name='house_no',
            field=models.CharField(max_length=100, null=True),
        ),
        migrations.AlterField(
            model_name='center',
            name='email',
            field=models.CharField(max_length=50),
        ),
        migrations.AlterField(
            model_name='volounteer',
            name='Center_id',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, to='center.center'),
        ),
        migrations.AlterField(
            model_name='volounteer',
            name='designation',
            field=models.CharField(max_length=255, null=True),
        ),
        migrations.AlterField(
            model_name='volounteer',
            name='qualification',
            field=models.CharField(max_length=255, null=True),
        ),
        migrations.DeleteModel(
            name='CenterRequest',
        ),
        migrations.DeleteModel(
            name='CenterShipment',
        ),
        migrations.DeleteModel(
            name='PhoneCenter',
        ),
    ]
