# Generated by Django 5.1.1 on 2024-10-02 16:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('center', '0002_remove_phonecenter_center_id_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='center',
            name='email',
            field=models.EmailField(max_length=254),
        ),
    ]
