# Generated by Django 5.1.1 on 2024-10-28 17:10

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('center', '0003_alter_center_email'),
        ('item', '0008_remove_itempickup_donor_request_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='VolounteerPickup',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('assigned_time', models.DateTimeField(auto_now_add=True)),
                ('timestamp', models.DateTimeField()),
                ('pickup_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='item.itempickup')),
                ('volunteer', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='center.volounteer')),
            ],
        ),
    ]
