# Generated by Django 5.1.1 on 2024-10-29 09:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('center', '0004_volounteerpickup'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='volounteerpickup',
            name='timestamp',
        ),
        migrations.AddField(
            model_name='volounteerpickup',
            name='isPicked',
            field=models.BooleanField(default=False),
        ),
    ]
