# Generated by Django 5.1.1 on 2024-10-29 10:34

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('center', '0005_remove_volounteerpickup_timestamp_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='volounteerpickup',
            name='volunteer',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='center.volounteer'),
        ),
    ]
