# Generated by Django 5.1.1 on 2024-10-30 14:35

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('center', '0009_inventory'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='volounteer',
            name='house_no',
        ),
    ]
