# Generated by Django 5.1.1 on 2024-10-31 05:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('center', '0010_remove_volounteer_house_no'),
    ]

    operations = [
        migrations.AlterField(
            model_name='inventory',
            name='inventory_id',
            field=models.CharField(max_length=50),
        ),
    ]
