# Generated by Django 5.1.1 on 2024-11-01 09:11

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('center', '0011_alter_inventory_inventory_id'),
        ('item', '0011_remove_itemreceive_itemreceive_id_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='CenterRequest',
            fields=[
                ('req_id', models.CharField(max_length=20, primary_key=True, serialize=False)),
                ('quantity', models.IntegerField()),
                ('isShipped', models.BooleanField(default=False)),
                ('isReceived', models.BooleanField(default=False)),
                ('request_time', models.DateTimeField(auto_now_add=True, null=True)),
                ('center', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='center.center')),
                ('item_type', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='item.itemtype')),
            ],
        ),
        migrations.CreateModel(
            name='CenterShipping',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('shipped_time', models.DateTimeField(auto_now_add=True, null=True)),
                ('c_request', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='center.centerrequest')),
                ('from_center', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='center.center')),
            ],
        ),
        migrations.CreateModel(
            name='CenterReceive',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('timestamp', models.DateTimeField(auto_now_add=True)),
                ('center', models.ForeignKey(null=True, on_delete=django.db.models.deletion.PROTECT, to='center.center')),
                ('item_type', models.ForeignKey(null=True, on_delete=django.db.models.deletion.PROTECT, to='item.itemtype')),
                ('ShippingID', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='center.centershipping')),
            ],
        ),
    ]
