# Generated by Django 5.1.1 on 2024-11-01 10:20

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('center', '0012_centerrequest_centershipping_centerreceive'),
    ]

    operations = [
        migrations.RenameField(
            model_name='centershipping',
            old_name='from_center',
            new_name='to_center',
        ),
    ]
