# Generated by Django 5.1.1 on 2024-11-01 12:10

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('center', '0012_centerrequest_centershipping_centerreceive'),
    ]

    operations = [
        migrations.AddField(
            model_name='centerreceive',
            name='quantity',
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name='centerreceive',
            name='req_id',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.PROTECT, to='center.centerrequest'),
        ),
    ]
