# Generated by Django 5.1.1 on 2024-11-01 13:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('center', '0013_centerreceive_quantity_centerreceive_req_id'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='inventory',
            name='id',
        ),
        migrations.AlterField(
            model_name='inventory',
            name='inventory_id',
            field=models.CharField(max_length=50, primary_key=True, serialize=False),
        ),
    ]
