# Generated by Django 5.1.1 on 2024-11-01 14:08

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('center', '0014_remove_inventory_id_alter_inventory_inventory_id'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='centershipping',
            name='from_center',
        ),
    ]
