# Generated by Django 5.1.1 on 2024-11-01 14:09

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('center', '0015_remove_centershipping_from_center'),
    ]

    operations = [
        migrations.AddField(
            model_name='centershipping',
            name='from_center',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='center.center'),
        ),
    ]
