# Generated by Django 5.1.1 on 2024-11-01 17:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('center', '0016_centershipping_from_center'),
    ]

    operations = [
        migrations.AddField(
            model_name='centerreceive',
            name='isComplete',
            field=models.BooleanField(default=False),
        ),
    ]
