# Generated by Django 5.1.1 on 2024-10-30 14:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('beneficiary', '0002_alter_beneficiaryrequest_request_time'),
    ]

    operations = [
        migrations.AlterField(
            model_name='beneficiary',
            name='address',
            field=models.TextField(null=True),
        ),
    ]
