# Generated by Django 5.1.1 on 2024-11-02 07:12

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('beneficiary', '0003_alter_beneficiary_address'),
        ('center', '0018_remove_centerreceive_iscomplete_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='beneficiaryrequest',
            name='isDeliverd',
            field=models.BooleanField(default=False),
        ),
        migrations.CreateModel(
            name='BeneficiaryShipment',
            fields=[
                ('bship_id', models.AutoField(primary_key=True, serialize=False)),
                ('isDelivered', models.BooleanField(default=False)),
                ('shipment_time', models.DateTimeField(auto_now_add=True)),
                ('BR_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='shipments', to='beneficiary.beneficiaryrequest')),
                ('V_id', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='deliveries', to='center.volounteer')),
            ],
        ),
    ]
