# Generated by Django 5.1.1 on 2024-11-02 07:26

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('beneficiary', '0004_beneficiaryrequest_isdeliverd_beneficiaryshipment'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='beneficiaryrequest',
            name='isDeliverd',
        ),
    ]
